In [111]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from sklearn.model_selection import train_test_split
from pandas.core.common import random_state
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score, classification_report

In [68]:
df = pd.read_csv("Iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [102]:
df.isnull().sum()

SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [98]:
df = df.dropna()
df.dtypes

SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [100]:
def remove_outliers(df, column, species):
    subset_df = df[df['Species'] == species]
    Q1 = subset_df[column].quantile(0.25)
    Q3 = subset_df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df.loc[(df['Species'] == species) & ((df[column] < lower_bound) | (df[column] > upper_bound)), column] = None

    return df

In [101]:
df = remove_outliers(df, 'PetalWidthCm', 'Iris-setosa')
df = remove_outliers(df, 'SepalWidthCm', 'Iris-virginica')
df = remove_outliers(df, 'PetalLengthCm', 'Iris-setosa')

In [103]:
X = df.drop('Species', axis=1)
y = df['Species']  


In [108]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
nb = GaussianNB()
nb.fit(X_train, y_train)

y_pred = nb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.9629629629629629


In [110]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

accuracy = np.trace(cm) / np.sum(cm)
print("Accuracy:", accuracy)

precision_0 = cm[0, 0] / np.sum(cm[0, :])
print("Precision (Class 0):", precision_0)

precision_1 = cm[1, 1] / np.sum(cm[1, :])
print("Precision (Class 1):", precision_1)

precision_2 = cm[2, 2] / np.sum(cm[2, :])
print("Precision (Class 2):", precision_2)

error_rate = 1 - accuracy
print("Error Rate:", error_rate)

recall_0 = cm[0, 0] / np.sum(cm[:, 0])
print("Recall (Class 0):", recall_0)

recall_1 = cm[1, 1] / np.sum(cm[:, 1])
print("Recall (Class 1):", recall_1)

recall_2 = cm[2, 2] / np.sum(cm[:, 2])
print("Recall (Class 2):", recall_2)


[[ 9  0  0]
 [ 0 10  0]
 [ 0  1  7]]
Accuracy: 0.9629629629629629
Precision (Class 0): 1.0
Precision (Class 1): 1.0
Precision (Class 2): 0.875
Error Rate: 0.03703703703703709
Recall (Class 0): 1.0
Recall (Class 1): 0.9090909090909091
Recall (Class 2): 1.0


In [112]:

report = classification_report(y_test, y_pred)
print(report)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.91      1.00      0.95        10
 Iris-virginica       1.00      0.88      0.93         8

       accuracy                           0.96        27
      macro avg       0.97      0.96      0.96        27
   weighted avg       0.97      0.96      0.96        27

